apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - runtime-config.yaml
commonLabels:
  app.kubernetes.io/part-of: tropical-management
  app.kubernetes.io/managed-by: argocd
