apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - runtime-config.yaml
  - ingress.yaml

    # workloads
  - workloads/tropical-api-gateway.yaml
  - workloads/tropical-auth.yaml
  - workloads/tropical-audit.yaml
  - workloads/tropical-inventory.yaml
  - workloads/tropical-sales.yaml
  - workloads/tropical-dashboard.yaml
  - workloads/tropical-chat.yaml
  - workloads/tropical-web.yaml

  # database migration hook
  - jobs/tropical-db-migrator.yaml

  # services
  - services/tropical-api-gateway.yaml
  - services/tropical-auth.yaml
  - services/tropical-audit.yaml
  - services/tropical-inventory.yaml
  - services/tropical-sales.yaml
  - services/tropical-dashboard.yaml
  - services/tropical-chat.yaml
  - services/tropical-web.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: tropical-management
      app.kubernetes.io/managed-by: argocd
