apiVersion: v1
kind: ConfigMap
metadata:
  name: tropical-runtime-config
data:
  AUTH_SERVICE_URL: http://tropical-auth:8080
  AUDIT_SERVICE_URL: http://tropical-audit:8080
  INVENTORY_SERVICE_URL: http://tropical-inventory:8080
  SALES_SERVICE_URL: http://tropical-sales:8080
  DASHBOARD_SERVICE_URL: http://tropical-dashboard:8080
  WORKFORCE_SERVICE_URL: http://tropical-workforce:8080
