apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-app
resources:
  - ../../base

commonLabels:
  app.kubernetes.io/part-of: tropical-management
  environment: test

patchesStrategicMerge:
  - tropical-chat-vault.yaml
  - tropical-sales-vault.yaml
  - tropical-inventory-vault.yaml
  - tropical-audit-vault.yaml
  - tropical-api-gateway-vault.yaml
  - tropical-auth-vault.yaml

images:
  - name: harbor-dt.co.id/devops-apps/tropical-auth
    newTag: 1.0.0-beta2-45f0ef90ddbc
  - name: harbor-dt.co.id/devops-apps/tropical-audit
    newTag: 1.0.0-beta2-45f0ef90ddbc
  - name: harbor-dt.co.id/devops-apps/tropical-inventory
    newTag: 1.0.0-beta2-45f0ef90ddbc
  - name: harbor-dt.co.id/devops-apps/tropical-sales
    newTag: 1.0.0-beta2-45f0ef90ddbc
  - name: harbor-dt.co.id/devops-apps/tropical-chat
    newTag: 1.0.0-beta2-45f0ef90ddbc
  - name: harbor-dt.co.id/devops-apps/tropical-dashboard
    newTag: 1.0.0-beta2-45f0ef90ddbc
  - name: harbor-dt.co.id/devops-apps/tropical-api-gateway
    newTag: 1.0.0-beta2-45f0ef90ddbc
  - name: harbor-dt.co.id/devops-apps/tropical-web
    newTag: 1.0.0-beta2-45f0ef90ddbc