apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-app
resources:
  - ../../base

commonLabels:
  app.kubernetes.io/part-of: tropical-management
  environment: test

patchesStrategicMerge:
  - tropical-chat-vault.yaml
  - tropical-sales-vault.yaml
  - tropical-inventory-vault.yaml
  - tropical-audit-vault.yaml
  - tropical-api-gateway-vault.yaml
  - tropical-auth-vault.yaml
