apiVersion: apps/v1
kind: Deployment
metadata:
  name: tropical-web
spec:
  template:
    spec:
      containers:
        - name: tropical-web
          image: harbor-dt.co.id/devops-apps/tropical-web:0687ae33e513
