apiVersion: apps/v1
kind: Deployment
metadata:
  name: tropical-web
spec:
  template:
    spec:
      containers:
        - name: tropical-web
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 750m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
