apiVersion: apps/v1
kind: Deployment
metadata:
  name: tropical-workforce

spec:
  replicas: 0
  selector:
    matchLabels:
      app: tropical-workforce
  template:
    metadata:
      labels:
        app: tropical-workforce
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: tropical-management
      containers:
      - name: tropical-workforce
        image: harbor-dt.co.id/devops-apps/tropical-workforce:v1
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /livez
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 24
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: WORKFORCE_DB_DSN
          value: tropical:tropical@tcp(192.168.100.70:3306)/tropical_inventory?parseTime=true&charset=utf8mb4
