apiVersion: apps/v1
kind: Deployment
metadata:
  name: tropical-sales

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tropical-sales
  template:
    metadata:
      labels:
        app: tropical-sales
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: tropical-management
      containers:
      - name: tropical-sales
        image: harbor-dt.co.id/devops-apps/tropical-sales:v1
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /livez
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 24
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: SALES_DB_DSN
          value: tropical:tropical@tcp(192.168.100.70:3306)/tropical_sales?parseTime=true&charset=utf8mb4